#!/bin/bash
# A basic munin-node plugin to monitor the Raspberry Pi CPU frequency.

if [ "$1" == "autoconf" ]; then
     if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Raspberry Pi Frequency"
     echo "graph_vlabel Frequency in MHz"
     echo "graph_category Sensors"
     echo "cpu.label CPU"
else
     echo "cpu.value $(( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)/1000 ))"
fi
