#!/bin/bash
# A basic munin-node plugin for AOSONG DHT11, DHT22, AM2302 sensors.
# Temperature and Humidity

# USAGE
# Please make the symlink as rpi-dht-sensor_TYPE_GPIOPIN
# Example rpi-dht-sensor_2302_24

sensor_GPIO=${0##*/rpi-dht-sensor_*_}
sensor_TYPE=${0##*/rpi-dht-sensor_}

#echo $sensor_GPIO
#echo ${sensor_TYPE%_*}

#function read_SENSOR {
#    data=$( /usr/local/bin/Adafruit_DHT ${sensor_TYPE%_*} $sensor_GPIO | tail -1 )
#    if [[ "$data" =~ "Data" ]]; then
#	return "#E#"
#    else
#        return "humidity.value ${data:23:4}\ntemp.value ${data:8:4}"
#    fi
#}



if [[ ! "11 22 2302" =~ "${sensor_TYPE%_*}" ]]; then
    echo "Please add a sensor type to the symlink. See usage!"
elif [[ ! "$sensor_GPIO" =~ [0-9] ]]; then
    echo "Please specify the GPIO pin!"
elif [ "$1" == "autoconf" ]; then
     if [ -e /usr/local/bin/Adafruit_DHT ]; then
         echo "yes"
     else
         echo "no"
         exit 1
     fi
elif [ "$1" == "config" ]; then
     echo "graph_title Raspberry Pi Aosong ${sensor_TYPE%_*} Sensor"
     echo "graph_vlabel Humidity and Temperature"
     echo "graph_category Sensors"
     echo "temp.warning 30"
     echo "temp.critical 40"
     echo "temp.label Temperature in Celsius"
     echo "humidity.label Humidity in Percent"
     echo "err.label	Error Counter"
else
    OK=0
    while [ "$OK" -gt -1 ]; do
	data=$( /usr/local/bin/Adafruit_DHT ${sensor_TYPE%_*} $sensor_GPIO | tail -1 )
        if [[ "$data" =~ "Data" ]]; then
	    sleep 1
#	    echo $data
	    ((OK++))
        elif [[ "${sensor_TYPE%_*}" =~ "11" ]]; then
	    echo "humidity.value ${data:20:2}"
	    echo "temp.value ${data:7:2}"
	    echo "err.value $OK"
	    OK=-1;
	else
	    echo "humidity.value ${data:23:4}"
	    echo "temp.value ${data:8:4}"
	    echo "err.value $OK"
	    OK=-1;
        fi
    done
fi

